---
# tasks file for zk.postfix
- name: Install PostFix package
  package:
    name: postfix
    state: installed
- name: Start/Enable PostFix service
  service:
    name: postfix
    state: started
    enabled: yes
- name: Start/enable firewalld
  service:
    name: firewalld
    state: started
    enabled: yes
    
- name: Create the PostFix main.cf
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
  notify: restart postfix service
- name: allow smtp service in the firewall
  firewalld:
    service: smtp
    state: enabled
    permanent: yes
- name: Reload firewalld
  command: firewall-cmd --reload
  changed_when: false
